### ISSUE TITLE
After formatting INNER JOIN turn into JOIN

### ISSUE THREAD

**Issue by diulin** [dnsmkl/fsqlf#16]
Thank you for beautified SQL queries.
 
When formatting query with INNER JOIN, keyword INNER disappears. 

Example:

select * 
from a
inner join b
on a.a = b.b

SELECT *
FROM a
JOIN b
 ON a.a=b.b

Can you, please, direct me how can I keep INNER keyword in formatted queries?

**Comment by Shoelace** [comment]
i get the same on the 0.03 precompiled version.

the word OUTER also dissapears from

    select * 
    from a
    left outer join b
    on a.a = b.b

becomes


    SELECT
      *
    FROM a
    LEFT JOIN b
     ON a.a=b.b

**Comment by diulin** [comment]
Technically INNER JOIN is equivalent to JOIN and LEFT (RIGHT) OUTER JOIN to LEFT (RIGHT) JOIN, but I would like to have an option to leave or not redundant keywords.

**Comment by dnsmkl** [comment]
This answer is long overdue, but anyway...

For to keep original keyword text (e.g. "left outer join"):
- in gui there is checkbox "Use original text".
- in command line, there is option `fsqlf --keyword-text original`.
